# Generated by Django 5.1.4 on 2025-01-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_tag_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="view_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
